services :
  debian-ci :
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./check.sh:/root/check.sh"
    command: "/root/check.sh"